Feature/homework register
lanlh2023/blog-homework pull request #4
Opened 2023-10-27 08:49 UTC by lanlh2023

# Feature register account
## Validate form UI and serve.
![image](https://github.com/lanlh2023/blog-homework/assets/147787873/81a322c6-c292-43b5-b483-e76027e3ba9d)
## Send notification to slack.
![image](https://github.com/lanlh2023/blog-homework/assets/147787873/a849f580-9bcc-4c35-a3ca-86750efc3f7b)
![image](https://github.com/lanlh2023/blog-homework/assets/147787873/01c15dc7-117b-493f-8808-3f79d1aed777)
## Insert new record in database.
![image](https://github.com/lanlh2023/blog-homework/assets/147787873/275d1078-f546-454c-a6db-a8982a19dbf1)

2023-10-30 05:57 UTC, huyndzigexn requested changes

2023-10-30 05:57 UTC, huyndzigexn commented on app/Http/Requests/RegisterUserRequest.php
> +        $requriedOrNullableForPasswordConfirm = isset($this->password) ? 'required' : 'nullable';
Đã dùng `same:password` rồi thì ko cần dùng cái này

2023-10-30 05:57 UTC, huyndzigexn commented on app/Repositories/RepositoryEloquent/UserRepository.php
> +            ->get();
dùng `first` luôn em

2023-10-30 05:57 UTC, huyndzigexn commented on app/Http/Controllers/Admin/UserController.php
> +        if ($users->count() > 0) {
Đã get bên `getByEmail` thì mình chỉ cần check `if($users)` thôi là được rồi

2023-10-30 06:25 UTC, Thanhhm-dev commented on app/Helpers/User.php
> +  function getMessage($key, $paramArray = []) {
lưu ý space e nhé, 4 hết nha
với helper bên laravel có, e sử dụng theo cấu trúc fw nha, không viết chay như này á.

2023-10-30 06:25 UTC, Thanhhm-dev commented on app/Http/Controllers/Admin/UserController.php
> +use Illuminate\Support\Facades\Config;
e dùng helper config() xem, không phải add thêm vào

2023-10-30 06:28 UTC, Thanhhm-dev commented on app/Http/Controllers/Admin/UserController.php
> +    public function checkDuplicateEmail(Request $request) {
class với function để { ở dòng mới giúp a nha

2023-10-30 06:28 UTC, Thanhhm-dev commented on app/Http/Requests/RegisterUserRequest.php
> +                'unique:users,email,'.$id,
space e nhé

2023-10-30 06:33 UTC, Thanhhm-dev commented on app/Repositories/RepositoryEloquent/UserRepository.php
>          return [];
ở đây e có thể return ở line 43 luôn, vì khi gọi tới function này e đã có 1 thao tác check if rồi, nên ở đây không cần thiết

2023-10-30 06:33 UTC, Thanhhm-dev commented on resources/views/blog/index.blade.php
> +    @if(! is_null(session('message')))
chỉnh space lại e nhé

2023-10-30 06:34 UTC, Thanhhm-dev commented on app/Models/User.php
> +   {
space e nhé

2023-10-30 06:36 UTC, Thanhhm-dev commented on app/Http/Controllers/Admin/UserController.php
> +        return Response::json(false);
return true/false như vậy e có thể rút gọn lại thành Response::json($users->exists()); hoặc count gì đó vd == 0 thì sẽ không phải check lại 2 lần, nhìn sẽ gọn hơn

2023-10-30 07:54 UTC, huyndzigexn commented on app/Http/Requests/RegisterUserRequest.php
> +                'unique:users,email,'.$id,
tách ra vậy nè em 'unique:users,email,' . $id,

2023-10-30 07:57 UTC, lanlh2023 commented on app/Http/Requests/RegisterUserRequest.php
> +                'unique:users,email,'.$id,
unique: users, email, ' . $id,
Là vầy hay sao anh

2023-10-30 08:04 UTC, lanlh2023 commented on app/Http/Requests/RegisterUserRequest.php
> +                'unique:users,email,'.$id,
Em hiểu rồi ạ

2023-10-30 08:28 UTC, huyndzigexn commented on app/Http/Requests/RegisterUserRequest.php
> +                'unique:users,email,' . $id,
bỏ dấu phẩy

2023-10-30 08:28 UTC, huyndzigexn commented on app/Http/Controllers/Admin/UserController.php
>              if($request->session()->get('previous_url')) {
add space

2023-10-30 08:28 UTC, huyndzigexn commented on resources/js/validation/register-form.js
> +                        if(data == 'true') {
add space

2023-10-30 08:28 UTC, huyndzigexn commented on resources/js/validation/register-form.js
> +            if($(form).data('is-submitted') === undefined) {
add space

2023-10-30 08:42 UTC, huyndzigexn commented on app/Http/Requests/RegisterUserRequest.php
> +                'unique:users,email,' . $id,
bỏ dấu phẩy sau `email`

2023-10-30 09:05 UTC, huyndzigexn commented
LGTM

2023-10-30 09:06 UTC, merged

2023-12-13 04:52 UTC, leviethung-zigexn commented on app/Helpers/User.php
> +    public static function getMessage($key, $paramArray = [])
mong muốn khai báo kiểu dữ liệu cho data input và output

2023-12-13 04:52 UTC, leviethung-zigexn commented on app/Http/Controllers/Admin/UserController.php
> +        $user = new User;
Tại sao controller lại. có khai báo model `User`

2023-12-13 04:52 UTC, leviethung-zigexn commented on app/Http/Controllers/Admin/UserController.php
> +        $users = $this->userRepository->getByEmail($request->email);
Chỉ để check `true` or `false` thì nên viết 1 query check dùng `exist()` sẽ tối ưu về query hơn

2023-12-13 04:52 UTC, leviethung-zigexn commented on app/Http/Controllers/Admin/UserController.php
> +        return Response::json(!empty($users));
Cái này đã viết kiểu global sử dụng format chung cho response api rồi chứ ?

2023-12-13 04:52 UTC, leviethung-zigexn commented on app/Notifications/RegisterNotification.php
> +        //
Nếu ko sử dụng thì nên xoá

2023-12-13 04:52 UTC, leviethung-zigexn commented on app/Notifications/RegisterNotification.php
> +    public function toSlack($notifiable)
yêu. cầu comment mục đích sử dụng của từng function

2023-12-13 04:52 UTC, leviethung-zigexn commented on app/Notifications/RegisterNotification.php
> +        $content = "New user registration "."\n".
có thể sử dụng sprinf ko ?

2023-12-13 04:52 UTC, leviethung-zigexn commented on app/Notifications/RegisterNotification.php
> +    public function toArray(object $notifiable): array
function này có sử dụng không ? Nếu ko thì xoá

2023-12-13 04:52 UTC, leviethung-zigexn commented on resources/js/libs/jquery/jquery-validation/custom-method.js
> +        return this.optional(element) || (size !== NaN && element.files[0].size <= size)
`element.files[0].size` dữ liệu luôn luôn có `size` chứ ?